### ISSUE TITLE
Status Outputs

### ISSUE THREAD

**Issue by nisupa135** [priiduonu/ihcclient#2]
Thank you very much for your work. I was able to integrate my old system, and it works correctly in Home Assistant. The only problem is that I cannot see the status of the outputs; they do not update.  If I action the output from Home Assistant, it works, but if, for example, a light is turned on or off with a switch or another system, it does not show as on. Is there a solution? On the IHCServer Webinterface, the status of the output is visible and changes correctly.

**Comment by priiduonu** [comment]
Thanks,

If everything is configured correctly, it should work regardless of which method was used to change the IHC module output status.

Can you post the relevant config sections for the outputs (for Home Assistant: `command_lines.yaml`, main `configuration.yaml`, for IHCclient: `modules.yaml`, `settings.yaml`)?

**Comment by nisupa135** [comment]
Thank you for replying, this is what i have in the files: 
command_lines.yaml

```
- switch: 
    name: 1_1
    command_on: curl --silent 'http://192.168.1.110:8081/ihcrequest' --data-binary '{"type":"setOutput","moduleNumber":1,"ioNumber":1,"state":true}'
    command_off: curl --silent 'http://192.168.1.110:8081/ihcrequest' --data-binary '{"type":"setOutput","moduleNumber":1,"ioNumber":1,"state":false}'
  
- switch: 
    name: 1_2
    command_on: curl --silent 'http://192.168.1.110:8081/ihcrequest' --data-binary '{"type":"setOutput","moduleNumber":1,"ioNumber":2,"state":true}'
    command_off: curl --silent 'http://192.168.1.110:8081/ihcrequest' --data-binary '{"type":"setOutput","moduleNumber":1,"ioNumber":2,"state":false}'
  
- switch: 
    name: 1_3
    command_on: curl --silent 'http://192.168.1.110:8081/ihcrequest' --data-binary '{"type":"setOutput","moduleNumber":1,"ioNumber":3,"state":true}'
    command_off: curl --silent 'http://192.168.1.110:8081/ihcrequest' --data-binary '{"type":"setOutput","moduleNumber":1,"ioNumber":3,"state":false}'
```
  

**configuration.yaml**


```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
command_line: !include command_lines.yaml
shell_command: !include shell_commands.yaml
homeassistant: 
  customize: !include customize.yaml

```
modules.yaml
```
#######################################
# outputs
#######################################

# IHC output module 1, output 1
# llum pilot sofa
- type: outputState
  moduleNumber: 1
  ioNumber: 1
  entity: switch.1_1

# IHC output module 1, output 2
# llum zona estar
- type: outputState
  moduleNumber: 1
  ioNumber: 2
  entity: switch.1_2

# IHC output module 1, output 3
# llum zona estar totes
- type: outputState
  moduleNumber: 1
  ioNumber: 3
  entity: switch.1_3

```

settings.yaml
```
# yaml configuration file for ihcclient

# IHCServer settings
ihc:
  server: 192.168.1.110
  port: 8081
  username:
  password:

# HASS server settings
hass:
  server: 192.168.1.111
  port: 8123
  token: xxxx (i have the real token here)

# logfile name:
log_file: /var/log/ihc.log


```

Let's see if we're lucky and can find what's wrong.
